// lib/executives.ts — All Executive Agent Definitions

import { Executive } from '@/types'

export const EXECUTIVES: Executive[] = [
  {
    role: 'CEO',
    name: 'Chief Executive Officer',
    emoji: '👑',
    color: '#4f8ef7',
    bg: 'rgba(79,142,247,0.15)',
    description: 'Vision, strategy & final decisions',
    responsibilities: ['Vision & strategy', 'Competitive positioning', 'Fundraising', 'Stakeholder management', 'Growth opportunities'],
    status: 'active',
    currentTask: 'Defining product vision for SmartCart',
    confidence: 94,
  },
  {
    role: 'CTO',
    name: 'Chief Technology Officer',
    emoji: '⚙️',
    color: '#22d3ee',
    bg: 'rgba(34,211,238,0.15)',
    description: 'Architecture, engineering & GitLab',
    responsibilities: ['System architecture', 'Engineering roadmap', 'Security & infra', 'GitLab management', 'Tech hiring'],
    status: 'thinking',
    currentTask: 'Designing microservices architecture',
    confidence: 88,
  },
  {
    role: 'CFO',
    name: 'Chief Financial Officer',
    emoji: '💰',
    color: '#22c55e',
    bg: 'rgba(34,197,94,0.15)',
    description: 'Finance, runway & fundraising',
    responsibilities: ['Revenue forecasting', 'Burn rate management', 'Pricing models', 'Financial risk', 'Investor relations'],
    status: 'active',
    currentTask: 'Modeling 18-month runway scenarios',
    confidence: 91,
  },
  {
    role: 'COO',
    name: 'Chief Operating Officer',
    emoji: '⚡',
    color: '#fb923c',
    bg: 'rgba(251,146,60,0.15)',
    description: 'Operations, execution & scale',
    responsibilities: ['Process optimization', 'Vendor management', 'OKR tracking', 'Logistics', 'Bottleneck resolution'],
    status: 'active',
    currentTask: 'Optimizing delivery operations flow',
    confidence: 86,
  },
  {
    role: 'CMO',
    name: 'Chief Marketing Officer',
    emoji: '📣',
    color: '#e879f9',
    bg: 'rgba(232,121,249,0.15)',
    description: 'Marketing, brand & growth',
    responsibilities: ['Brand strategy', 'Customer acquisition', 'Content & SEO', 'Social media', 'Launch campaigns'],
    status: 'thinking',
    currentTask: 'Crafting India launch GTM strategy',
    confidence: 89,
  },
  {
    role: 'CHRO',
    name: 'Chief HR Officer',
    emoji: '👥',
    color: '#fbbf24',
    bg: 'rgba(251,191,36,0.15)',
    description: 'People, culture & hiring',
    responsibilities: ['Talent acquisition', 'Org design', 'Culture building', 'Performance mgmt', 'Compensation'],
    status: 'active',
    currentTask: 'Defining engineering hiring plan',
    confidence: 85,
  },
  {
    role: 'CSO',
    name: 'Chief Strategy Officer',
    emoji: '🔭',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.15)',
    description: 'Long-term strategy & expansion',
    responsibilities: ['Market analysis', 'Partnership strategy', 'Geographic expansion', 'M&A opportunities', 'Competitive intelligence'],
    status: 'active',
    currentTask: 'Analyzing competitor landscape',
    confidence: 92,
  },
  {
    role: 'CPO',
    name: 'Chief Product Officer',
    emoji: '🎯',
    color: '#2dd4bf',
    bg: 'rgba(45,212,191,0.15)',
    description: 'Product, roadmap & user experience',
    responsibilities: ['Product strategy', 'Feature prioritization', 'User research', 'OKRs & metrics', 'Product-market fit'],
    status: 'thinking',
    currentTask: 'Prioritizing MVP feature roadmap',
    confidence: 87,
  },
]

export const COLLAB_MESSAGES = [
  { exec: 'CEO', color: '#4f8ef7', bg: 'rgba(79,142,247,0.2)', msg: 'SmartCart should target premium urban segment first — faster unit economics, higher LTV.' },
  { exec: 'CFO', color: '#22c55e', bg: 'rgba(34,197,94,0.2)', msg: 'At ₹850 AOV and 18% margin we need 4,200 orders/month to break even by month 8.' },
  { exec: 'CTO', color: '#22d3ee', bg: 'rgba(34,211,238,0.2)', msg: 'Created smartcart-backend repo + 3 milestones in GitLab. Sprint 1 covers auth, catalog, order APIs.' },
  { exec: 'CMO', color: '#e879f9', bg: 'rgba(232,121,249,0.2)', msg: 'Mumbai + Bangalore first — highest UPI adoption. Influencer + performance mix targeting ₹25-40L income bracket.' },
  { exec: 'CHRO', color: '#fbbf24', bg: 'rgba(251,191,36,0.2)', msg: 'Need 2 senior backend engineers, 1 ML engineer in Q3. Drafting JDs with Gemini today.' },
  { exec: 'CSO', color: '#a78bfa', bg: 'rgba(167,139,250,0.2)', msg: 'Zepto and Blinkit are vulnerable on premium segment. AI reordering is a genuine moat — lean in.' },
  { exec: 'COO', color: '#fb923c', bg: 'rgba(251,146,60,0.2)', msg: 'Shadowfax partnership cuts delivery cost by 40% vs owned fleet. Strongly recommend this path.' },
  { exec: 'CPO', color: '#2dd4bf', bg: 'rgba(45,212,191,0.2)', msg: 'Smart reorder must be the hero feature — one-tap AI prediction is the magic moment for users.' },
]

export const TIMELINE_ITEMS = [
  { status: 'done', text: 'Business idea received & analyzed', time: '2m ago' },
  { status: 'done', text: 'Market research completed',          time: '4m ago' },
  { status: 'done', text: 'Financial model generated',          time: '5m ago' },
  { status: 'done', text: 'Technical architecture designed',    time: '6m ago' },
  { status: 'running', text: 'GitLab workspace configuring',   time: 'Now'    },
  { status: 'pending', text: 'Sprint 1 plan generation',        time: 'Queued' },
  { status: 'pending', text: 'Marketing strategy',              time: 'Queued' },
  { status: 'pending', text: 'Hiring plan finalization',        time: 'Queued' },
]
